name       : qt5-declarative
version    : 5.9.2
release    : 12
source     :
    - https://download.qt.io/official_releases/qt/5.9/5.9.2/submodules/qtdeclarative-opensource-src-5.9.2.tar.xz : 0d40fd4de9c73b9173d8308c0dc37952bf5c747d87ff221962dd2f848d820b08
license    :
    - LGPL-2.1
    - LGPL-3.0
    - GFDL-1.3
    - GPL-3.0
component  : desktop.qt
summary    : Qt 5 Declarative Library
description: |
    Qt is a set of libraries for developing applications. This package contains base tools, like string, xml, and network handling.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Network)
    - pkgconfig(Qt5Test)
    - pkgconfig(Qt5XmlPatterns)
patterns   :
    - demos :
        - /usr/lib64/qt5/examples
setup      : |
    %patch -p1 < $pkgfiles/0001-Revert-Fix-qml-cache-invalidation-when-changing-depe.patch
    %patch -p1 < $pkgfiles/0001-Revert-Fix-crashes-with-closures-created-in-QML-comp.patch
    %qmake CONFIG+=release qtdeclarative.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
