name       : qt5-declarative
version    : 5.11.1
release    : 16
source     :
    - https://mirrors.ocf.berkeley.edu/qt/official_releases/qt/5.11/5.11.1/submodules/qtdeclarative-everywhere-src-5.11.1.tar.xz : 9ecf5ef6bf618fcb6719a4b22e3d9f9ce7623c2344667038171d5662624c4f3a
license    :
    - LGPL-2.1
    - LGPL-3.0
    - GFDL-1.3
    - GPL-3.0
component  : desktop.qt
summary    : Qt 5 Declarative Library
description: |
    Qt is a set of libraries for developing applications. This package contains base tools, like string, xml, and network handling.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Network)
    - pkgconfig(Qt5Test)
    - pkgconfig(Qt5XmlPatterns)
patterns   :
    - demos :
        - /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtdeclarative.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
