name       : qt5-declarative
version    : 5.13.1
release    : 22
source     :
    - https://download.qt.io/official_releases/qt/5.13/5.13.1/submodules/qtdeclarative-everywhere-src-5.13.1.tar.xz : ae3477401b13d6b31e8569629d3f73b3e81e27cec27595988ffd320eaec7f0e2
license    :
    - LGPL-2.1
    - LGPL-3.0
    - GFDL-1.3
    - GPL-3.0
component  : desktop.qt
summary    : Qt 5 Declarative Library
description: |
    Qt is a set of libraries for developing applications. This package contains base tools, like string, xml, and network handling.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Network)
    - pkgconfig(Qt5Test)
patterns   :
    - demos :
        - /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtdeclarative.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
