name       : qt5-declarative
version    : 5.11.0
release    : 15
source     :
    - http://qt.mirror.constant.com/official_releases/qt/5.11/5.11.0/submodules/qtdeclarative-everywhere-src-5.11.0.tar.xz : eea9378b17b1c16d3b5235629b9128349bf98cba7d9c61122653d976b25f57c0
license    :
    - LGPL-2.1
    - LGPL-3.0
    - GFDL-1.3
    - GPL-3.0
component  : desktop.qt
summary    : Qt 5 Declarative Library
description: |
    Qt is a set of libraries for developing applications. This package contains base tools, like string, xml, and network handling.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Network)
    - pkgconfig(Qt5Test)
    - pkgconfig(Qt5XmlPatterns)
patterns   :
    - demos :
        - /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtdeclarative.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
