name       : qt5-declarative
version    : 5.12.2
release    : 19
source     :
    - https://download.qt.io/official_releases/qt/5.12/5.12.2/submodules/qtdeclarative-everywhere-src-5.12.2.tar.xz : 470568745602e7fa21cdca42b1641162e4257cfeb7a2dcf8af24538c9516cc5b
license    :
    - LGPL-2.1
    - LGPL-3.0
    - GFDL-1.3
    - GPL-3.0
component  : desktop.qt
summary    : Qt 5 Declarative Library
description: |
    Qt is a set of libraries for developing applications. This package contains base tools, like string, xml, and network handling.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Network)
    - pkgconfig(Qt5Test)
patterns   :
    - demos :
        - /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtdeclarative.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
