name       : qt5-declarative
version    : 5.15.1
release    : 26
source     :
    - https://download.qt.io/official_releases/qt/5.15/5.15.1/submodules/qtdeclarative-everywhere-src-5.15.1.tar.xz : 7e30f0ccba61f9d71720b91d7f7523c23677f23cd96065cb71df1b0df329d768
homepage   : https://www.qt.io
license    :
    - LGPL-3.0-or-later
    - LGPL-3.0-or-later
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
component  : desktop.qt
summary    : Qt 5 Declarative Library
description: |
    Qt is a set of libraries for developing applications. This package contains base tools, like string, xml, and network handling.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Network)
    - vulkan-headers
patterns   :
    - demos :
        - /usr/lib64/qt5/examples
setup      : |
    %patch -p1 < $pkgfiles/qquickviews.patch
    %qmake CONFIG+=release qtdeclarative.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir -j1
