name       : qt5-declarative
version    : 5.10.0
release    : 14
source     :
    - https://download.qt.io/official_releases/qt/5.10/5.10.0/submodules/qtdeclarative-everywhere-src-5.10.0.tar.xz : 5ccb4dbca5046554037bcffbb05918f6efcff321c44cd1c39b1c47be7e67711e
license    :
    - LGPL-2.1
    - LGPL-3.0
    - GFDL-1.3
    - GPL-3.0
component  : desktop.qt
summary    : Qt 5 Declarative Library
description: |
    Qt is a set of libraries for developing applications. This package contains base tools, like string, xml, and network handling.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Network)
    - pkgconfig(Qt5Test)
    - pkgconfig(Qt5XmlPatterns)
patterns   :
    - demos :
        - /usr/lib64/qt5/examples
setup      : |
    %patch -p1 < $pkgfiles/Avoid-marking-hidden-windows-as-updatePending.patch
    %qmake CONFIG+=release qtdeclarative.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
