name       : qt5-declarative
version    : 5.13.2
release    : 23
source     :
    - https://download.qt.io/official_releases/qt/5.13/5.13.2/submodules/qtdeclarative-everywhere-src-5.13.2.tar.xz : d9a524f45fe9e136cda2252f9d7013ec17046d907e3f39606db920987c22d1fd
license    :
    - LGPL-2.1
    - LGPL-3.0
    - GFDL-1.3
    - GPL-3.0
component  : desktop.qt
summary    : Qt 5 Declarative Library
description: |
    Qt is a set of libraries for developing applications. This package contains base tools, like string, xml, and network handling.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Network)
    - pkgconfig(Qt5Test)
patterns   :
    - demos :
        - /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtdeclarative.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
