name       : qt5-declarative
version    : 5.15.2
release    : 28
source     :
    - https://download.qt.io/official_releases/qt/5.15/5.15.2/submodules/qtdeclarative-everywhere-src-5.15.2.tar.xz : c600d09716940f75d684f61c5bdaced797f623a86db1627da599027f6c635651
homepage   : https://www.qt.io
license    :
    - LGPL-3.0-or-later
    - LGPL-3.0-or-later
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt 5 Declarative Library
description: |
    Qt is a set of libraries for developing applications. This package contains base tools, like string, xml, and network handling.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Network)
    - vulkan-headers
patterns   :
    - demos :
        - /usr/lib64/qt5/examples
setup      : |
    %patch -p1 < $pkgfiles/qquickviews.patch
    %qmake CONFIG+=release qtdeclarative.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir -j1
